/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "exec.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>

data_out *
exec_1_svc(char **argp, struct svc_req *rqstp)
{
	static data_out  result;
	int fdout[2];
	int fderr[2];
	int pid;

	if((pipe(fdout) == -1) || (pipe(fderr) == -1))
		perror("Pipe");
	if((pid = fork()) == -1)
		perror("Fork");
	else if (pid == 0){ //transfer captured and sent to parrent process
		int r;
		close(fdout[0]);
		close(fderr[0]);
		dup2(fdout[1], STDOUT_FILENO);
		dup2(fderr[1], STDERR_FILENO);
		r = system(*argp);
		exit(r);
	}
	else{
		int n;
		int status;
		char buf [1024];

		close(fdout[1]);
		close(fderr[1]);
		n = read(fdout[0],result.std_out,1024);
		result.std_out[n] = '\0';

		n = read(fderr[0],result.std_err,1024);
		result.std_err[n] = '\0';

		wait(&status);
		result.exec_result = WEXITSTATUS(status);

		return &result;
	}
}
