/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EXEC_H_RPCGEN
#define _EXEC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data_out {
	int exec_result;
	char std_out[1024];
	char std_err[512];
};
typedef struct data_out data_out;

#define PROGRAM 0x31240000
#define EXEC 1

#if defined(__STDC__) || defined(__cplusplus)
#define EXEC 1
extern  data_out * exec_1(char **, CLIENT *);
extern  data_out * exec_1_svc(char **, struct svc_req *);
extern int program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define EXEC 1
extern  data_out * exec_1();
extern  data_out * exec_1_svc();
extern int program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data_out (XDR *, data_out*);

#else /* K&R C */
extern bool_t xdr_data_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EXEC_H_RPCGEN */
